// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package blockchain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash                 []byte               `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Prevhash             []byte               `protobuf:"bytes,3,opt,name=prevhash,proto3" json:"prevhash,omitempty"`
	Nonce                uint64               `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Target               []byte               `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Pubkey               string               `protobuf:"bytes,6,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Txs                  []*Tx                `protobuf:"bytes,7,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetPrevhash() []byte {
	if m != nil {
		return m.Prevhash
	}
	return nil
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Block) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *Block) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Chain struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain.Unmarshal(m, b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return xxx_messageInfo_Chain.Size(m)
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type NodeID struct {
	// pubkey is the public key of the client
	Pubkey string `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// id is the unique identifier of a node within a pool; a collection of nodes
	// mining for the same pubkey
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeID) Reset()         { *m = NodeID{} }
func (m *NodeID) String() string { return proto.CompactTextString(m) }
func (*NodeID) ProtoMessage()    {}
func (*NodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *NodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeID.Unmarshal(m, b)
}
func (m *NodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeID.Marshal(b, m, deterministic)
}
func (m *NodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeID.Merge(m, src)
}
func (m *NodeID) XXX_Size() int {
	return xxx_messageInfo_NodeID.Size(m)
}
func (m *NodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeID.DiscardUnknown(m)
}

var xxx_messageInfo_NodeID proto.InternalMessageInfo

func (m *NodeID) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *NodeID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Tx struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                float64              `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	For                  string               `protobuf:"bytes,3,opt,name=for,proto3" json:"for,omitempty"`
	From                 string               `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Hash                 []byte               `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{3}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Tx) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Tx) GetFor() string {
	if m != nil {
		return m.For
	}
	return ""
}

func (m *Tx) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Tx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Tx) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type DiscoverRequest struct {
	NodeID *NodeID `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	// returnAddr is the path back to the requesting peer so the responding peer
	// can connect back. Current methods for discovering request ip not reliable within
	// Docker container
	ReturnAddr string `protobuf:"bytes,2,opt,name=returnAddr,proto3" json:"returnAddr,omitempty"`
	// peerAddrs is the collection of addresses of known nodes.
	// They can be used to further discover more peers
	KnownAddrs           []string `protobuf:"bytes,3,rep,name=knownAddrs,proto3" json:"knownAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverRequest) Reset()         { *m = DiscoverRequest{} }
func (m *DiscoverRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoverRequest) ProtoMessage()    {}
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{4}
}

func (m *DiscoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverRequest.Unmarshal(m, b)
}
func (m *DiscoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverRequest.Marshal(b, m, deterministic)
}
func (m *DiscoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverRequest.Merge(m, src)
}
func (m *DiscoverRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoverRequest.Size(m)
}
func (m *DiscoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverRequest proto.InternalMessageInfo

func (m *DiscoverRequest) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *DiscoverRequest) GetReturnAddr() string {
	if m != nil {
		return m.ReturnAddr
	}
	return ""
}

func (m *DiscoverRequest) GetKnownAddrs() []string {
	if m != nil {
		return m.KnownAddrs
	}
	return nil
}

type DiscoverResponse struct {
	NodeID *NodeID `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	// ok signifies to the pinger that it is ok to connect with and share
	// new tx and block solve propagations
	Ok bool `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// peerAddrs is the collection of addresses of other known nodes.
	// They can be used to further discover more peers
	KnownAddrs           []string `protobuf:"bytes,3,rep,name=knownAddrs,proto3" json:"knownAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverResponse) Reset()         { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()    {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{5}
}

func (m *DiscoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverResponse.Unmarshal(m, b)
}
func (m *DiscoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverResponse.Marshal(b, m, deterministic)
}
func (m *DiscoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverResponse.Merge(m, src)
}
func (m *DiscoverResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverResponse.Size(m)
}
func (m *DiscoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverResponse proto.InternalMessageInfo

func (m *DiscoverResponse) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *DiscoverResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *DiscoverResponse) GetKnownAddrs() []string {
	if m != nil {
		return m.KnownAddrs
	}
	return nil
}

type ShareChainRequest struct {
	NodeID *NodeID `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Chain  *Chain  `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	// returnAddr is the path back to the requesting peer so the responding peer
	// can connect back. Current methods for discovering request ip not reliable within
	// Docker container
	ReturnAddr           string   `protobuf:"bytes,3,opt,name=returnAddr,proto3" json:"returnAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareChainRequest) Reset()         { *m = ShareChainRequest{} }
func (m *ShareChainRequest) String() string { return proto.CompactTextString(m) }
func (*ShareChainRequest) ProtoMessage()    {}
func (*ShareChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{6}
}

func (m *ShareChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareChainRequest.Unmarshal(m, b)
}
func (m *ShareChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareChainRequest.Marshal(b, m, deterministic)
}
func (m *ShareChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareChainRequest.Merge(m, src)
}
func (m *ShareChainRequest) XXX_Size() int {
	return xxx_messageInfo_ShareChainRequest.Size(m)
}
func (m *ShareChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShareChainRequest proto.InternalMessageInfo

func (m *ShareChainRequest) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *ShareChainRequest) GetChain() *Chain {
	if m != nil {
		return m.Chain
	}
	return nil
}

func (m *ShareChainRequest) GetReturnAddr() string {
	if m != nil {
		return m.ReturnAddr
	}
	return ""
}

type ShareChainResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareChainResponse) Reset()         { *m = ShareChainResponse{} }
func (m *ShareChainResponse) String() string { return proto.CompactTextString(m) }
func (*ShareChainResponse) ProtoMessage()    {}
func (*ShareChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{7}
}

func (m *ShareChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareChainResponse.Unmarshal(m, b)
}
func (m *ShareChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareChainResponse.Marshal(b, m, deterministic)
}
func (m *ShareChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareChainResponse.Merge(m, src)
}
func (m *ShareChainResponse) XXX_Size() int {
	return xxx_messageInfo_ShareChainResponse.Size(m)
}
func (m *ShareChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShareChainResponse proto.InternalMessageInfo

func (m *ShareChainResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

type ShareTxRequest struct {
	NodeID *NodeID `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Tx     *Tx     `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	// returnAddr is the path back to the requesting peer so the responding peer
	// can connect back. Current methods for discovering request ip not reliable within
	// Docker container
	ReturnAddr           string   `protobuf:"bytes,3,opt,name=returnAddr,proto3" json:"returnAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareTxRequest) Reset()         { *m = ShareTxRequest{} }
func (m *ShareTxRequest) String() string { return proto.CompactTextString(m) }
func (*ShareTxRequest) ProtoMessage()    {}
func (*ShareTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{8}
}

func (m *ShareTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareTxRequest.Unmarshal(m, b)
}
func (m *ShareTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareTxRequest.Marshal(b, m, deterministic)
}
func (m *ShareTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareTxRequest.Merge(m, src)
}
func (m *ShareTxRequest) XXX_Size() int {
	return xxx_messageInfo_ShareTxRequest.Size(m)
}
func (m *ShareTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShareTxRequest proto.InternalMessageInfo

func (m *ShareTxRequest) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *ShareTxRequest) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *ShareTxRequest) GetReturnAddr() string {
	if m != nil {
		return m.ReturnAddr
	}
	return ""
}

type ShareTxResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareTxResponse) Reset()         { *m = ShareTxResponse{} }
func (m *ShareTxResponse) String() string { return proto.CompactTextString(m) }
func (*ShareTxResponse) ProtoMessage()    {}
func (*ShareTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{9}
}

func (m *ShareTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareTxResponse.Unmarshal(m, b)
}
func (m *ShareTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareTxResponse.Marshal(b, m, deterministic)
}
func (m *ShareTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareTxResponse.Merge(m, src)
}
func (m *ShareTxResponse) XXX_Size() int {
	return xxx_messageInfo_ShareTxResponse.Size(m)
}
func (m *ShareTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShareTxResponse proto.InternalMessageInfo

func (m *ShareTxResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func init() {
	proto.RegisterType((*Block)(nil), "blockchain.Block")
	proto.RegisterType((*Chain)(nil), "blockchain.Chain")
	proto.RegisterType((*NodeID)(nil), "blockchain.NodeID")
	proto.RegisterType((*Tx)(nil), "blockchain.Tx")
	proto.RegisterType((*DiscoverRequest)(nil), "blockchain.DiscoverRequest")
	proto.RegisterType((*DiscoverResponse)(nil), "blockchain.DiscoverResponse")
	proto.RegisterType((*ShareChainRequest)(nil), "blockchain.ShareChainRequest")
	proto.RegisterType((*ShareChainResponse)(nil), "blockchain.ShareChainResponse")
	proto.RegisterType((*ShareTxRequest)(nil), "blockchain.ShareTxRequest")
	proto.RegisterType((*ShareTxResponse)(nil), "blockchain.ShareTxResponse")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0xda, 0xb1, 0x9b, 0x4c, 0x51, 0xda, 0xae, 0x2a, 0x64, 0xb9, 0xa5, 0x58, 0xbe, 0x10,
	0x90, 0x70, 0x4a, 0x7a, 0xe1, 0x4a, 0x29, 0x07, 0x84, 0xc4, 0x61, 0xc9, 0x89, 0xdb, 0xc6, 0xd9,
	0x26, 0x56, 0x9a, 0x5d, 0xe3, 0x5d, 0x17, 0x23, 0xc1, 0x9d, 0xaf, 0xe0, 0xbf, 0xb8, 0xf0, 0x2d,
	0xc8, 0x63, 0xd7, 0x36, 0x69, 0x51, 0x44, 0xb9, 0xed, 0xcc, 0x7b, 0xbb, 0xef, 0xcd, 0x1b, 0x27,
	0xb0, 0x97, 0x66, 0xca, 0xa8, 0x31, 0x4f, 0x93, 0x08, 0x4f, 0x14, 0x66, 0x57, 0x2a, 0x5e, 0xc5,
	0x4b, 0x9e, 0x48, 0xff, 0x78, 0xa1, 0xd4, 0xe2, 0x4a, 0x94, 0xe8, 0x98, 0x4b, 0xa9, 0x0c, 0x37,
	0x89, 0x92, 0xba, 0x62, 0xfa, 0x8f, 0x6b, 0x14, 0xab, 0x59, 0x7e, 0x39, 0x36, 0xc9, 0x5a, 0x68,
	0xc3, 0xd7, 0x69, 0x45, 0x08, 0x7f, 0x12, 0x70, 0xce, 0xcb, 0xd7, 0xe8, 0x4b, 0x18, 0x34, 0xa0,
	0x47, 0x02, 0x32, 0xda, 0x9d, 0xf8, 0x51, 0x75, 0x3d, 0xba, 0xb9, 0x1e, 0x4d, 0x6f, 0x18, 0xac,
	0x25, 0x53, 0x0a, 0xbd, 0x25, 0xd7, 0x4b, 0xcf, 0x0a, 0xc8, 0xe8, 0x01, 0xc3, 0x33, 0xf5, 0xa1,
	0x9f, 0x66, 0xe2, 0x1a, 0xfb, 0x36, 0xf6, 0x9b, 0x9a, 0x1e, 0x82, 0x23, 0x95, 0x8c, 0x85, 0xd7,
	0x0b, 0xc8, 0xa8, 0xc7, 0xaa, 0x82, 0x3e, 0x04, 0xd7, 0xf0, 0x6c, 0x21, 0x8c, 0xe7, 0x20, 0xbf,
	0xae, 0xca, 0x7e, 0x9a, 0xcf, 0x56, 0xe2, 0x8b, 0xe7, 0x06, 0x64, 0x34, 0x60, 0x75, 0x45, 0x03,
	0xb0, 0x4d, 0xa1, 0xbd, 0x9d, 0xc0, 0x1e, 0xed, 0x4e, 0x86, 0x51, 0x1b, 0x49, 0x34, 0x2d, 0x58,
	0x09, 0x85, 0x13, 0x70, 0x5e, 0x97, 0x0d, 0xfa, 0x14, 0x5c, 0x84, 0xb5, 0x47, 0x90, 0x7d, 0xd0,
	0x65, 0xe3, 0xf4, 0xac, 0x26, 0x84, 0xa7, 0xe0, 0xbe, 0x57, 0x73, 0xf1, 0xf6, 0xa2, 0xa3, 0x4b,
	0xfe, 0xd0, 0x1d, 0x82, 0x95, 0xcc, 0x71, 0x56, 0x87, 0x59, 0xc9, 0x3c, 0xfc, 0x41, 0xc0, 0x9a,
	0x16, 0xff, 0x11, 0xdf, 0x21, 0x38, 0xd7, 0xfc, 0x2a, 0x17, 0xf8, 0x26, 0x61, 0x55, 0x41, 0xf7,
	0xc1, 0xbe, 0x54, 0x19, 0x66, 0x37, 0x60, 0xe5, 0xb1, 0x8c, 0xf9, 0x32, 0x53, 0x6b, 0x4c, 0x6d,
	0xc0, 0xf0, 0x5c, 0x9a, 0x31, 0x0a, 0x03, 0x1b, 0x30, 0xcb, 0xa8, 0x66, 0x15, 0x6e, 0xbb, 0x8a,
	0xf0, 0x1b, 0xec, 0x5d, 0x24, 0x3a, 0x56, 0xd7, 0x22, 0x63, 0xe2, 0x53, 0x2e, 0xb4, 0xa1, 0xcf,
	0xc0, 0x95, 0x38, 0x65, 0xed, 0x94, 0x76, 0x03, 0xa9, 0xe6, 0x67, 0x35, 0x83, 0x9e, 0x00, 0x64,
	0xc2, 0xe4, 0x99, 0x7c, 0x35, 0x9f, 0x67, 0xe8, 0x71, 0xc0, 0x3a, 0x9d, 0x12, 0x5f, 0x49, 0xf5,
	0x19, 0x0b, 0xed, 0xd9, 0x81, 0x5d, 0xe2, 0x6d, 0x27, 0x94, 0xb0, 0xdf, 0xca, 0xeb, 0x54, 0x49,
	0x2d, 0xfe, 0x49, 0x7f, 0x08, 0x96, 0x5a, 0xa1, 0x6e, 0x9f, 0x59, 0x6a, 0xb5, 0x55, 0xef, 0x3b,
	0x81, 0x83, 0x0f, 0x4b, 0x9e, 0x09, 0xdc, 0xfd, 0x7d, 0x26, 0x7e, 0x02, 0x0e, 0xf6, 0x51, 0x74,
	0xe3, 0x6b, 0xa9, 0x1e, 0xad, 0xf0, 0x8d, 0x68, 0xec, 0xcd, 0x68, 0xc2, 0x53, 0xa0, 0x5d, 0x27,
	0xf5, 0xf0, 0x3e, 0xf4, 0x79, 0x1c, 0x8b, 0xd4, 0x88, 0x39, 0x9a, 0xe9, 0xb3, 0xa6, 0x0e, 0xbf,
	0xc2, 0x10, 0x6f, 0x4c, 0x8b, 0xfb, 0xad, 0xca, 0x32, 0x45, 0xed, 0x7a, 0xf3, 0x17, 0x61, 0x99,
	0x62, 0xab, 0xdf, 0xe7, 0xb0, 0xd7, 0xa8, 0x6f, 0x37, 0x3b, 0xf9, 0x45, 0xa0, 0x57, 0x3a, 0xa0,
	0x6f, 0xa0, 0x7f, 0xb3, 0x62, 0x7a, 0xd4, 0xd5, 0xdd, 0xf8, 0xee, 0xfc, 0xe3, 0xbb, 0xc1, 0x5a,
	0xeb, 0x1d, 0x40, 0x1b, 0x17, 0x7d, 0xd4, 0xe5, 0xde, 0x5a, 0xa8, 0x7f, 0xf2, 0x37, 0xb8, 0x7e,
	0xec, 0x1c, 0x76, 0xea, 0x59, 0xa8, 0x7f, 0x8b, 0xda, 0xc4, 0xeb, 0x1f, 0xdd, 0x89, 0x55, 0x6f,
	0x9c, 0x9f, 0x7d, 0x7c, 0xb1, 0x48, 0xcc, 0x32, 0x9f, 0x45, 0xb1, 0x5a, 0x8f, 0xb9, 0x5e, 0xf0,
	0x44, 0x0a, 0x3d, 0x6e, 0x6f, 0x54, 0xff, 0xab, 0x0b, 0xd5, 0x69, 0xcd, 0x5c, 0xec, 0x9d, 0xfd,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x9e, 0xe4, 0xa7, 0xb6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	ShareChain(ctx context.Context, in *ShareChainRequest, opts ...grpc.CallOption) (*ShareChainResponse, error)
	ShareTx(ctx context.Context, in *ShareTxRequest, opts ...grpc.CallOption) (*ShareTxResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Node/Discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ShareChain(ctx context.Context, in *ShareChainRequest, opts ...grpc.CallOption) (*ShareChainResponse, error) {
	out := new(ShareChainResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Node/ShareChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ShareTx(ctx context.Context, in *ShareTxRequest, opts ...grpc.CallOption) (*ShareTxResponse, error) {
	out := new(ShareTxResponse)
	err := c.cc.Invoke(ctx, "/blockchain.Node/ShareTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	ShareChain(context.Context, *ShareChainRequest) (*ShareChainResponse, error)
	ShareTx(context.Context, *ShareTxRequest) (*ShareTxResponse, error)
}

// UnimplementedNodeServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServer struct {
}

func (*UnimplementedNodeServer) Discover(ctx context.Context, req *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (*UnimplementedNodeServer) ShareChain(ctx context.Context, req *ShareChainRequest) (*ShareChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareChain not implemented")
}
func (*UnimplementedNodeServer) ShareTx(ctx context.Context, req *ShareTxRequest) (*ShareTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareTx not implemented")
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Node/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ShareChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ShareChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Node/ShareChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ShareChain(ctx, req.(*ShareChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ShareTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ShareTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.Node/ShareTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ShareTx(ctx, req.(*ShareTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _Node_Discover_Handler,
		},
		{
			MethodName: "ShareChain",
			Handler:    _Node_ShareChain_Handler,
		},
		{
			MethodName: "ShareTx",
			Handler:    _Node_ShareTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
