// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asgaines/blockchain/mining (interfaces: Miner)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	chain "github.com/asgaines/blockchain/chain"
	mining "github.com/asgaines/blockchain/mining"
	blockchain "github.com/asgaines/blockchain/protogo/blockchain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMiner is a mock of Miner interface
type MockMiner struct {
	ctrl     *gomock.Controller
	recorder *MockMinerMockRecorder
}

// MockMinerMockRecorder is the mock recorder for MockMiner
type MockMinerMockRecorder struct {
	mock *MockMiner
}

// NewMockMiner creates a new mock instance
func NewMockMiner(ctrl *gomock.Controller) *MockMiner {
	mock := &MockMiner{ctrl: ctrl}
	mock.recorder = &MockMinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMiner) EXPECT() *MockMinerMockRecorder {
	return m.recorder
}

// AddTx mocks base method
func (m *MockMiner) AddTx(arg0 *blockchain.Tx) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTx", arg0)
}

// AddTx indicates an expected call of AddTx
func (mr *MockMinerMockRecorder) AddTx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockMiner)(nil).AddTx), arg0)
}

// Mine mocks base method
func (m *MockMiner) Mine(arg0 context.Context, arg1 chan<- mining.BlockReport) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Mine", arg0, arg1)
}

// Mine indicates an expected call of Mine
func (mr *MockMinerMockRecorder) Mine(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mine", reflect.TypeOf((*MockMiner)(nil).Mine), arg0, arg1)
}

// ResetTxs mocks base method
func (m *MockMiner) ResetTxs() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetTxs")
}

// ResetTxs indicates an expected call of ResetTxs
func (mr *MockMinerMockRecorder) ResetTxs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetTxs", reflect.TypeOf((*MockMiner)(nil).ResetTxs))
}

// SetPrevBlock mocks base method
func (m *MockMiner) SetPrevBlock(arg0 *chain.Block) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPrevBlock", arg0)
}

// SetPrevBlock indicates an expected call of SetPrevBlock
func (mr *MockMinerMockRecorder) SetPrevBlock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrevBlock", reflect.TypeOf((*MockMiner)(nil).SetPrevBlock), arg0)
}

// SetTarget mocks base method
func (m *MockMiner) SetTarget(arg0 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTarget", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTarget indicates an expected call of SetTarget
func (mr *MockMinerMockRecorder) SetTarget(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTarget", reflect.TypeOf((*MockMiner)(nil).SetTarget), arg0)
}
